"""Wave 16.4 — cuTile fused GDN (Gated DeltaNet) single-timestep decode.

Implements the GDN recurrent state update + output read in a single
@ct.kernel. For each (batch, head, d_v-block) grid cell:

    Load q[0:d_k], k[0:d_k], v[bv:bv+BV], alpha, beta   (f16)
    Load S_in[0:d_k, bv:bv+BV]                          (f32)
    Compute:
        u        = k^T · (α · S_in)                     (BV,)  f32
        residual = v - u                                (BV,)  f32
        S_out    = α·S_in  +  β · k ⊗ residual          (d_k, BV)  f32
        o        = q^T · S_out                          (BV,)  f32
    Store S_out, o

Grid: (batch * n_heads, d_v / BLOCK_V). No cross-block reductions —
each block owns its disjoint slice of d_v columns.

Per-head state tile memory:
  - d_k=64, BV=32:   64 · 32 · 4 = 8 KB   (correctness shape)
  - d_k=256, BV=64:  256 · 64 · 4 = 64 KB (Qwen3-Next decode shape)

The state tile is large; cuTile will probably spill through shared
memory (a single 256×64 f32 tile is right at the single-block shared-
memory budget on sm_120). Pick BV to keep the tile reasonable; a
smaller BV means more grid cells but smaller per-block state tile.

CLI:
    --smoke     correctness at SHAPE_CORRECTNESS
    --bench     timed at SHAPE_QWEN3_NEXT_DECODE (1 warmup + 50 iters)
    --csv-out FILE    bench CSV
    --export-cubin    write cubin for SASS inspection
"""
from __future__ import annotations

import argparse
import csv
import statistics
import sys
from pathlib import Path

import cuda.tile as ct
import cupy
import numpy as np
from cuda.tile.compilation import (
    ArrayConstraint,
    CallingConvention,
    KernelSignature,
    export_kernel,
)

# Hook the wave-15/16 shared infra.
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(
    0, str(REPO_ROOT / "analysis" / "wave15-attention-architecture" / "reference")
)
from shapes_gdn import GDNShape, SHAPE_CORRECTNESS, SHAPE_QWEN3_NEXT_DECODE  # noqa: E402

# Wave 22.15 — shape sweep. We mirror cutile-attn-kda's W22.7 SHAPE_REGISTRY
# pattern. Inputs for these shapes are generated by
# analysis/wave15-attention-architecture/reference/gen_w22_15_inputs.py and
# live in the shared inputs/ tree, same as qwen3_next_decode.
SHAPE_TINY  = GDNShape(name="tiny",  batch=1, n_heads=4,  d_k=64,  d_v=64)
SHAPE_SMALL = GDNShape(name="small", batch=1, n_heads=8,  d_k=128, d_v=128)
SHAPE_LARGE = GDNShape(name="large", batch=4, n_heads=64, d_k=256, d_v=256)
SHAPE_WIDE  = GDNShape(name="wide",  batch=1, n_heads=16, d_k=512, d_v=512)
SHAPE_REGISTRY: dict[str, GDNShape] = {
    SHAPE_QWEN3_NEXT_DECODE.name: SHAPE_QWEN3_NEXT_DECODE,
    SHAPE_TINY.name:  SHAPE_TINY,
    SHAPE_SMALL.name: SHAPE_SMALL,
    SHAPE_LARGE.name: SHAPE_LARGE,
    SHAPE_WIDE.name:  SHAPE_WIDE,
}
from flops_gdn import (  # noqa: E402
    gdn_decode_flops,
    gdn_decode_bytes,
    gdn_decode_gbps,
    gdn_decode_tflops,
)
from tolerances import get as get_tol  # noqa: E402

INPUTS_DIR = REPO_ROOT / "analysis" / "wave15-attention-architecture" / "inputs"

WARMUP = 2
ITERS = 50


# ─────────────────────────────────────────────────────────────────────────────
# Kernel factory
# ─────────────────────────────────────────────────────────────────────────────


def make_gdn_decode_kernel(D_K: int, D_V: int, BLOCK_V: int):
    """Build a @ct.kernel specialized to these GDN shape constants.

    Grid layout (caller picks):
        bid0 ∈ [0, B·H)         — flattened (batch, head)
        bid1 ∈ [0, D_V // BV)   — d_v-block index

    Array layouts:
        Q       (B*H, D_K)        f16   — tiled_view((1, D_K))
        K       (B*H, D_K)        f16   — tiled_view((1, D_K))
        V       (B*H, D_V)        f16   — tiled_view((1, BLOCK_V))
        alpha   (B*H, 1)          f16   — tiled_view((1, 1))
        beta    (B*H, 1)          f16   — tiled_view((1, 1))
        S_in    (B*H*D_K, D_V)    f32   — tiled_view((D_K, BLOCK_V)) with
                 row base = bh * D_K, col base = bv·BLOCK_V
        S_out   (B*H*D_K, D_V)    f32
        O       (B*H, D_V)        f16

    The per-block state tile is (D_K, BLOCK_V) f32. For D_K=256, BV=64
    this is 64 KB — at the edge of shared-mem feasibility.
    """
    D_V_BLOCKS = D_V // BLOCK_V

    @ct.kernel
    def gdn_decode(Q, K, V, Alpha, Beta, S_in, S_out, O):
        bh = ct.bid(0)   # flattened (batch, head)
        bv = ct.bid(1)   # d_v-block index

        # Tiled views for each 2D array.
        # Q, K are (B*H, D_K)  — one row per (batch, head).
        q_view = Q.tiled_view((1, D_K), padding_mode=ct.PaddingMode.ZERO)
        k_view = K.tiled_view((1, D_K), padding_mode=ct.PaddingMode.ZERO)
        # V, O are (B*H, D_V) — we load the BLOCK_V-slice for this bv.
        v_view = V.tiled_view((1, BLOCK_V), padding_mode=ct.PaddingMode.ZERO)
        o_view = O.tiled_view((1, BLOCK_V), padding_mode=ct.PaddingMode.ZERO)
        # alpha, beta: (B*H, 1)
        a_view = Alpha.tiled_view((1, 1), padding_mode=ct.PaddingMode.ZERO)
        b_view = Beta.tiled_view((1, 1), padding_mode=ct.PaddingMode.ZERO)
        # S_in, S_out: (B*H*D_K, D_V) — 2D flattened over (B*H) · D_K rows.
        # Row base for head (bh): bh * D_K. Col base for bv: bv * BLOCK_V.
        # But tiled_view((D_K, BLOCK_V)) uses tile indices, so the tile row
        # index for head bh is just bh (each head occupies one D_K-row tile).
        s_view = S_in.tiled_view((D_K, BLOCK_V), padding_mode=ct.PaddingMode.ZERO)
        s_out_view = S_out.tiled_view(
            (D_K, BLOCK_V), padding_mode=ct.PaddingMode.ZERO
        )

        # ── Load inputs ──
        # q, k are 1×D_K tiles (row-shape).
        q_tile = q_view.load((bh, 0))  # (1, D_K) f16
        k_tile = k_view.load((bh, 0))  # (1, D_K) f16
        v_tile = v_view.load((bh, bv))  # (1, BLOCK_V) f16
        a_tile = a_view.load((bh, 0))  # (1, 1) f16
        b_tile = b_view.load((bh, 0))  # (1, 1) f16

        # State tile: (D_K, BLOCK_V) f32.
        s_tile = s_view.load((bh, bv))  # (D_K, BLOCK_V) f32

        # Upcast scalars/vectors for the f32 accumulate path.
        k_f32 = k_tile.astype(ct.float32)    # (1, D_K)
        q_f32 = q_tile.astype(ct.float32)    # (1, D_K)
        v_f32 = v_tile.astype(ct.float32)    # (1, BLOCK_V)
        alpha_f32 = a_tile.astype(ct.float32)  # (1, 1)
        beta_f32 = b_tile.astype(ct.float32)   # (1, 1)

        # ── (1) S_scaled = alpha · S_in  ──
        s_scaled = s_tile * alpha_f32  # broadcast (1,1) over (D_K, BLOCK_V)

        # ── (2) u = k^T · S_scaled   (shape (1, BLOCK_V))  ──
        # k_f32 is (1, D_K); s_scaled is (D_K, BLOCK_V); result (1, BLOCK_V).
        u_acc = ct.zeros((1, BLOCK_V), ct.float32)
        u_acc = ct.mma(k_f32, s_scaled, u_acc)

        # ── (3) residual = v - u  ──
        residual = v_f32 - u_acc  # (1, BLOCK_V)

        # ── (4) S_out = S_scaled + beta · (k ⊗ residual)  ──
        # Outer product via mma: k^T (shape (D_K, 1)) · residual (1, BLOCK_V)
        # → (D_K, BLOCK_V).  ct.mma needs a matrix-shape pair; transpose k.
        k_col = ct.transpose(k_f32)  # (D_K, 1)
        outer_acc = ct.zeros((D_K, BLOCK_V), ct.float32)
        outer_acc = ct.mma(k_col, residual, outer_acc)

        s_out = s_scaled + beta_f32 * outer_acc

        # ── (5) o = q^T · S_out   (shape (1, BLOCK_V))  ──
        o_acc = ct.zeros((1, BLOCK_V), ct.float32)
        o_acc = ct.mma(q_f32, s_out, o_acc)

        # ── Store ──
        s_out_view.store((bh, bv), s_out)          # f32
        o_view.store((bh, bv), o_acc.astype(O.dtype))  # f16

    return gdn_decode


# ─────────────────────────────────────────────────────────────────────────────
# Input plumbing
# ─────────────────────────────────────────────────────────────────────────────


def load_inputs(shape: GDNShape):
    prefix = INPUTS_DIR / f"gdn_{shape.name}"
    return {
        "q": np.load(f"{prefix}_q_f16.npy"),
        "k": np.load(f"{prefix}_k_f16.npy"),
        "v": np.load(f"{prefix}_v_f16.npy"),
        "alpha": np.load(f"{prefix}_alpha_f16.npy"),
        "beta": np.load(f"{prefix}_beta_f16.npy"),
        "S_in": np.load(f"{prefix}_S_in_f32.npy"),
        "o_expected": np.load(f"{prefix}_o_expected_f16.npy"),
        "S_out_expected": np.load(f"{prefix}_S_out_expected_f32.npy"),
    }


def prepare_device(shape: GDNShape, inp: dict):
    B, H, d_k, d_v = shape.batch, shape.n_heads, shape.d_k, shape.d_v
    BH = B * H

    q_d = cupy.asarray(inp["q"].reshape(BH, d_k), dtype=cupy.float16)
    k_d = cupy.asarray(inp["k"].reshape(BH, d_k), dtype=cupy.float16)
    v_d = cupy.asarray(inp["v"].reshape(BH, d_v), dtype=cupy.float16)
    alpha_d = cupy.asarray(inp["alpha"].reshape(BH, 1), dtype=cupy.float16)
    beta_d = cupy.asarray(inp["beta"].reshape(BH, 1), dtype=cupy.float16)
    # State: (B, H, d_k, d_v) → (B*H*d_k, d_v)
    s_in_d = cupy.asarray(inp["S_in"].reshape(BH * d_k, d_v), dtype=cupy.float32)
    s_out_d = cupy.zeros((BH * d_k, d_v), dtype=cupy.float32)
    o_d = cupy.zeros((BH, d_v), dtype=cupy.float16)
    return q_d, k_d, v_d, alpha_d, beta_d, s_in_d, s_out_d, o_d


# ─────────────────────────────────────────────────────────────────────────────
# Block-size picker
# ─────────────────────────────────────────────────────────────────────────────


def pick_block_v(shape: GDNShape) -> int:
    """Pick BLOCK_V given the per-block state tile budget.

    Constraint: tile size D_K · BLOCK_V · 4 bytes must fit in a single
    shared-memory allocation (~192 KB safe on sm_120) but we want the
    tile to be matmul-friendly (multiple of 8 or 16).

    For d_k=64: BV=32 → 8 KB tile (tiny, fine).
    For d_k=256: BV=64 → 64 KB tile (fits comfortably).
    For d_k=512: BV=32 → 64 KB tile (`wide` shape; bigger BV would
    blow past the dynamic-smem cap on sm_120).
    """
    # Conservative: keep state tile ≤ 64 KB f32 = 16384 elements.
    max_elems = 16384
    # Must divide d_v evenly.
    for bv in (128, 64, 32, 16, 8):
        if shape.d_v % bv == 0 and shape.d_k * bv <= max_elems:
            return bv
    raise ValueError(f"no feasible BLOCK_V for d_k={shape.d_k} d_v={shape.d_v}")


# ─────────────────────────────────────────────────────────────────────────────
# Correctness smoke
# ─────────────────────────────────────────────────────────────────────────────


def run_smoke(shape: GDNShape) -> bool:
    print(
        f"[smoke] shape={shape.name} B={shape.batch} H={shape.n_heads} "
        f"d_k={shape.d_k} d_v={shape.d_v}"
    )
    inp = load_inputs(shape)
    q_d, k_d, v_d, a_d, b_d, s_in_d, s_out_d, o_d = prepare_device(shape, inp)

    bv = pick_block_v(shape)
    print(f"[smoke] BLOCK_V={bv}")
    kernel = make_gdn_decode_kernel(shape.d_k, shape.d_v, bv)
    grid = (shape.batch * shape.n_heads, shape.d_v // bv)
    stream = cupy.cuda.get_current_stream()

    ct.launch(
        stream.ptr, grid, kernel,
        (q_d, k_d, v_d, a_d, b_d, s_in_d, s_out_d, o_d),
    )
    cupy.cuda.runtime.deviceSynchronize()

    # Back to (B, H, ...) shape for comparison.
    B, H, d_k, d_v = shape.batch, shape.n_heads, shape.d_k, shape.d_v
    o_np = o_d.get().reshape(B, H, d_v)
    s_out_np = s_out_d.get().reshape(B, H, d_k, d_v)

    o_exp = inp["o_expected"]
    s_exp = inp["S_out_expected"]

    tol = get_tol("f16")
    # Output check (f16).
    abs_err_o = np.abs(o_np.astype(np.float32) - o_exp.astype(np.float32))
    max_o = float(abs_err_o.max())
    rel_o = max_o / (float(np.abs(o_exp).max()) + 1e-30)
    ok_o = np.allclose(
        o_np.astype(np.float32), o_exp.astype(np.float32),
        atol=tol.atol, rtol=tol.rtol,
    )
    print(f"[smoke] o    max_abs={max_o:.3e} rel={rel_o:.3e}  {'OK' if ok_o else 'FAIL'}")

    # State check (f32). Use loose f16-style tolerance scaled by d_k (matmul accum).
    abs_err_s = np.abs(s_out_np - s_exp)
    max_s = float(abs_err_s.max())
    rel_s = max_s / (float(np.abs(s_exp).max()) + 1e-30)
    # f32 state but computed from f16 inputs: tolerance ~ f16 level.
    ok_s = max_s < 5e-3 or rel_s < 5e-3
    print(f"[smoke] S_out max_abs={max_s:.3e} rel={rel_s:.3e}  {'OK' if ok_s else 'FAIL'}")

    if not (ok_o and ok_s):
        # Locate worst offender.
        if not ok_o:
            w = np.unravel_index(abs_err_o.argmax(), abs_err_o.shape)
            print(
                f"        worst o offender at {w}: "
                f"got={o_np[w]:.4f} expected={o_exp[w]:.4f}"
            )
        if not ok_s:
            w = np.unravel_index(abs_err_s.argmax(), abs_err_s.shape)
            print(
                f"        worst S offender at {w}: "
                f"got={s_out_np[w]:.6f} expected={s_exp[w]:.6f}"
            )
    return ok_o and ok_s


# ─────────────────────────────────────────────────────────────────────────────
# Bench
# ─────────────────────────────────────────────────────────────────────────────


def run_bench(shape: GDNShape, csv_path: str) -> None:
    print(
        f"[bench] shape={shape.name} B={shape.batch} H={shape.n_heads} "
        f"d_k={shape.d_k} d_v={shape.d_v}"
    )
    inp = load_inputs(shape)
    q_d, k_d, v_d, a_d, b_d, s_in_d, s_out_d, o_d = prepare_device(shape, inp)

    bv = pick_block_v(shape)
    print(f"[bench] BLOCK_V={bv}")
    kernel = make_gdn_decode_kernel(shape.d_k, shape.d_v, bv)
    grid = (shape.batch * shape.n_heads, shape.d_v // bv)
    print(f"[bench] grid={grid}  n_blocks={grid[0]*grid[1]}")
    stream = cupy.cuda.get_current_stream()

    flops = gdn_decode_flops(shape)
    bytes_ = gdn_decode_bytes(shape)
    print(f"[bench] flops/iter = {flops / 1e6:.3f} MFLOPS")
    print(f"[bench] bytes/iter = {bytes_ / 1024:.1f} KB")

    # Warmup (JIT compile + cache warm).
    for _ in range(WARMUP):
        ct.launch(
            stream.ptr, grid, kernel,
            (q_d, k_d, v_d, a_d, b_d, s_in_d, s_out_d, o_d),
        )
    cupy.cuda.runtime.deviceSynchronize()

    # Timed iters.
    starts = [cupy.cuda.Event() for _ in range(ITERS)]
    ends = [cupy.cuda.Event() for _ in range(ITERS)]
    for i in range(ITERS):
        starts[i].record(stream)
        ct.launch(
            stream.ptr, grid, kernel,
            (q_d, k_d, v_d, a_d, b_d, s_in_d, s_out_d, o_d),
        )
        ends[i].record(stream)
    stream.synchronize()

    ms_list = []
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow([
            "impl", "kernel", "batch", "n_heads", "d_k", "d_v",
            "block_v", "iter", "gpu_us", "gbps", "tflops",
        ])
        for i in range(ITERS):
            gpu_ms = cupy.cuda.get_elapsed_time(starts[i], ends[i])
            ms_list.append(gpu_ms)
            gbps = gdn_decode_gbps(shape, gpu_ms)
            tf = gdn_decode_tflops(shape, gpu_ms)
            if i < 3 or i == ITERS - 1:
                print(
                    f"[bench] iter={i:2d} gpu_us={gpu_ms*1000:.2f} "
                    f"gbps={gbps:.1f} tflops={tf:.3f}"
                )
            w.writerow([
                "cutile", "gdn_decode_fused", shape.batch, shape.n_heads,
                shape.d_k, shape.d_v, bv, i,
                f"{gpu_ms*1000:.3f}", f"{gbps:.3f}", f"{tf:.6f}",
            ])

    ms_sorted = sorted(ms_list)
    med = statistics.median(ms_list)
    q1 = ms_sorted[ITERS // 4]
    q3 = ms_sorted[(3 * ITERS) // 4]
    best = ms_sorted[0]
    med_gbps = gdn_decode_gbps(shape, med)
    best_gbps = gdn_decode_gbps(shape, best)
    best_tf = gdn_decode_tflops(shape, best)
    # RTX 5090 HBM3E peak is ~1.79 TB/s (1792 GB/s).
    peak_gbps = 1792.0

    print()
    print("=" * 72)
    print(f" BENCH SUMMARY — {shape.name} (B={shape.batch} H={shape.n_heads} "
          f"d_k={shape.d_k} d_v={shape.d_v})")
    print(f"   BLOCK_V={bv}  grid={grid}")
    print(f"   iters={ITERS}  warmup={WARMUP}")
    print(f"   median: {med*1000:.2f} us   {med_gbps:.1f} GB/s   "
          f"({med_gbps/peak_gbps:.1%} of 5090 HBM peak)")
    print(f"   IQR   : [{q1*1000:.2f}, {q3*1000:.2f}] us")
    print(f"   best  : {best*1000:.2f} us   {best_gbps:.1f} GB/s   "
          f"({best_gbps/peak_gbps:.1%} of peak)   {best_tf:.3f} TFLOPS")
    print(f"   headline: GB/s ({best_gbps:.1f}) — GDN decode is memory-bound")
    print("=" * 72)


# ─────────────────────────────────────────────────────────────────────────────
# Cubin export
# ─────────────────────────────────────────────────────────────────────────────


def _ac(dt):
    return ArrayConstraint(
        dtype=dt, ndim=2, index_dtype=ct.int32,
        stride_lower_bound_incl=0, alias_groups=(), may_alias_internally=False,
        stride_constant=(None, 1), stride_divisible_by=1,
        shape_divisible_by=1, base_addr_divisible_by=1,
    )


def export_cubin(out_path: str, shape: GDNShape) -> str | None:
    bv = pick_block_v(shape)
    kernel = make_gdn_decode_kernel(shape.d_k, shape.d_v, bv)
    sig = KernelSignature(
        parameters=[
            _ac(ct.float16),  # Q
            _ac(ct.float16),  # K
            _ac(ct.float16),  # V
            _ac(ct.float16),  # Alpha
            _ac(ct.float16),  # Beta
            _ac(ct.float32),  # S_in
            _ac(ct.float32),  # S_out
            _ac(ct.float16),  # O
        ],
        calling_convention=CallingConvention.cutile_python_v1(),
    )
    try:
        export_kernel(
            kernel, [sig], out_path,
            gpu_code="sm_120", output_format="cubin",
        )
        import os
        size = os.path.getsize(out_path)
        print(f"  wrote {out_path}  ({size} bytes)")
        return out_path
    except Exception as e:
        print(
            f"  FAILED cubin export: {type(e).__name__}: {str(e)[:600]}",
            file=sys.stderr,
        )
        return None


# ─────────────────────────────────────────────────────────────────────────────
# Entrypoint
# ─────────────────────────────────────────────────────────────────────────────


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--smoke", action="store_true", default=False)
    ap.add_argument("--bench", action="store_true", default=False)
    ap.add_argument("--export-cubin", action="store_true", default=False)
    ap.add_argument("--csv-out", default="results.csv")
    ap.add_argument("--cubin-out", default="gdn_decode_fused.cubin")
    # Wave 22.15 — shape sweep. Default keeps the legacy headline behaviour
    # (qwen3_next_decode); pass --shape NAME to bench any of the registry
    # shapes (qwen3_next_decode, tiny, small, large, wide).
    ap.add_argument(
        "--shape", default=SHAPE_QWEN3_NEXT_DECODE.name,
        choices=sorted(SHAPE_REGISTRY.keys()),
        help="Bench shape (default: qwen3_next_decode).",
    )
    args = ap.parse_args()

    if not (args.smoke or args.bench or args.export_cubin):
        args.smoke = True

    print(f"cuda-tile version: {ct.__version__}")
    print(f"cupy: {cupy.__version__}")
    props = cupy.cuda.runtime.getDeviceProperties(0)
    print(f"device: {props['name'].decode()}")
    print(f"compute capability: sm_{props['major']}{props['minor']}")
    print()

    bench_shape = SHAPE_REGISTRY[args.shape]

    rc = 0
    if args.smoke:
        ok = run_smoke(SHAPE_CORRECTNESS)
        if not ok:
            rc = 1
        print()

    if args.bench:
        run_bench(bench_shape, args.csv_out)
        print()

    if args.export_cubin:
        print(f"Exporting cubin at shape={bench_shape.name} for SASS inspection…")
        export_cubin(args.cubin_out, bench_shape)

    return rc


if __name__ == "__main__":
    sys.exit(main())
